title: recipes-md
baseurl: ""
language: "en"
primary-color: "#3f51b5"

permalink: pretty

collections:
  recipes:
    output: true

exclude:
  - README.md
  - LICENSE
  - workbox-config.js
  - assets/icons/maskabe-logo.png
  - assets/icons/md-icon-round-local-dining.svg

translation:
  en:
    ingredients: "Ingredients"
    directions: "Directions"
  de:
    ingredients: "Zutaten"
    directions: "Zubereitung"